### ISSUE TITLE
`item.get_cloned()`?

### ISSUE THREAD

**Issue by rljacobson** [Anders429/hashable_rc#1]
I want to be able to iterate over the `(key, value)`'s of a `HashMap` in which the key is a `HashableRc`, but with `HashableRc` I cannot get the original `Rc` back. Since `HashableRc` holds a clone of the `Rc`, it would be trivial to add a `get_cloned()` method to `HashableRc` for my use case. What do you think? Would you be agreeable to a PR?

**Comment by Anders429** [comment]
Thanks for the submission. I've approved, and just published to [crates.io](https://crates.io/crates/hashable_rc) as version 0.2.0.
